force-app/main/default/objects/copado__Project__c/copado__Project__c.object-meta.xml
<CustomObject>
    <description>Overall object for capturing the project details.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/copado__Promotion__c/copado__Promotion__c.object-meta.xml
<CustomObject>
    <description>This object tracks the changes that are promoted to the next Salesforce instance.</description>
    <label>Promotion</label>
    <nameField>
        <displayFormat>P{00000}</displayFormat>
        <label>Promotion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/copado__Test__c/copado__Test__c.object-meta.xml
<CustomObject>
    <description>Copado Object to spin a test scenario</description>
    <label>Test</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/copado__User_Story__c/copado__User_Story__c.object-meta.xml
<CustomObject>
    <description>Agile form of requirements gathering</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>User Story Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/copado__User_Story__c/fields/copado__Project__c.field-meta.xml
<CustomField>
    <fullName>copado__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Project where the User Story belongs.</description>
    <inlineHelpText>Project where the User Story belongs.</inlineHelpText>
    <label>Project</label>
    <referenceTo>copado__Project__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/copadoSnykQif__CalculateContextTest.cls
@isTest
private with sharing class CalculateContextTest {
    @isTest
    private static void testCalculate() {
        System.runAs([SELECT Id FROM User WHERE Username = 'username@myemail.com'][0]) {
            // Setup
            TestDataFactory.createDefaultTestData('Salesforce');
            copado__User_Story__c userStory = [SELECT Id, Name FROM copado__User_Story__c WHERE copado__Project__c = :TestDataFactory.project.Id AND copado__Base_Branch__c = ''];
            copado__User_Story__c userStoryWithBranch = [SELECT Id, Name FROM copado__User_Story__c WHERE copado__Project__c = :TestDataFactory.project.Id AND copado__Base_Branch__c = 'user'];
            copado__Promotion__c promotion = [SELECT Id, Name FROM copado__Promotion__c WHERE copado__Project__c = :TestDataFactory.project.Id];

            // Exercise: Run with copado__User_Story_Commit__c
            {
                CalculateContext context = new CalculateContext();
                String obj = context.execute(TestDataFactory.jobStepWithCommit.Id);
                Map<String, Object> result = (Map<String, Object>) JSON.deserializeUntyped(obj);
                Assert.areEqual('feature/' + userStory.Name, result.get('branch'));
                Assert.areEqual(userStory.Id, result.get('userStoryId'));
                Assert.areEqual('main', result.get('baseBranch'));
            }
            // Exercise: Run with copado__Test__c
            {
                CalculateContext context = new CalculateContext();
                String obj = context.execute(TestDataFactory.jobStepWithTest.Id);
                Map<String, Object> result = (Map<String, Object>) JSON.deserializeUntyped(obj);
                Assert.areEqual('feature/' + userStoryWithBranch.Name, result.get('branch'));
                Assert.areEqual(userStoryWithBranch.Id, result.get('userStoryId'));
                Assert.areEqual('user', result.get('baseBranch'));
            }
            // Exercise: Run with copado__Promotion__c
            {
                CalculateContext context = new CalculateContext();
                String obj = context.execute(TestDataFactory.jobStepWithPromotion.Id);
                Map<String, Object> result = (Map<String, Object>) JSON.deserializeUntyped(obj);
                Assert.areEqual('promotion/' + promotion.Name, result.get('branch'));
                Assert.areEqual(promotion.Id, result.get('promotionId'));
                Assert.areEqual('dev', result.get('baseBranch'));
            }
        }
    }

    @TestSetup
    private static void makeData() {
        User runAsUser = new User(
            LastName = 'UserLastName',
            Username = 'username@myemail.com',
            Email = 'username@myemail.com',
            Alias = 'MyAlias',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = UserInfo.getProfileId(),
            LanguageLocaleKey = 'en_US'
        );
        insert runAsUser;

        System.runAs(runAsUser) {
            copado.GlobalAPI copadoGlobalAPI = new copado.GlobalAPI();
            copado.GlobalAPI.UserLicense userLicense = new copado.GlobalAPI.UserLicense();
            userLicense.isCCMEnabled = true;
            userLicense.isCopadoEnabled = true;
            userLicense.userId = runAsUser.Id;
            copadoGlobalAPI.upsertCopadoLicense(userLicense);

            PermissionSetAssignment copado = new PermissionSetAssignment();
            copado.PermissionSetId = [SELECT Id, Name FROM PermissionSet WHERE Name = 'Copado_User' LIMIT 1].Id;
            copado.AssigneeId = runAsUser.Id;
            insert copado;
        }
    }
}